[package]
name = "user-tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpf-api = "0.1"
bpf-script = "0.1"
btf = "0.3"
btf-derive = "0.3"
